
export const sample_foods:any[]=[
     {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 250,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/new1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 70,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 90,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 100,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 270,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 300,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
   {
    id:'6',
    name: 'Paratha',
    price: 70,
    cookTime: '40-50',
    favorite: false,
    origins: ['India'],
    stars: 4.0,
    imageUrl: 'assets/food2.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
   {
    id:'6',
    name: 'Chhole Bhature',
    price: 80,
    cookTime: '40-50',
    favorite: false,
    origins: ['India'],
    stars: 4.0,
    imageUrl: 'assets/food1.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
   {
    id:'6',
    name: 'Sandwich',
    price: 70,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food3.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
   {
    id:'6',
    name: 'Noodles',
    price: 140,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food5.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
   {
    id:'6',
    name: 'Pasta',
    price: 150,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
   {
    id:'6',
    name: 'Veg Roll',
    price: 80,
    cookTime: '40-50',
    favorite: false,
    origins: ['Chine'],
    stars: 4.0,
    imageUrl: 'assets/food7.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

export const sample_tags: any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 2 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]

export const sample_users: any[] = [
  {
    name: 'Nitus',
    email: 'neetu@gmail.com',
    password: '12345',
    address: '123 Main St, City, Country',
    isAdmin: true
  },
  {
    name: 'John Doe',
    email: 'john@example.com',
    password: 'password123',
    address: '456 Elm St, City, Country',
    isAdmin: false
  },
  {
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'password123',
    address: '789 Oak St, City, Country',
    isAdmin: false
  }
]
